name: Python package

on: [push]

jobs:
  
  Test_of_Dockerfile_and_Docker_container: 
    runs-on: ubuntu-latest
    steps:  
    - uses: actions/checkout@v2
    - name: Create Docker image 
      run: |
        docker build -t app:latest .
    - name: Run Deocker container
      run: |
        docker run -d -p 5000:5000 app:latest
    - name: Test with pytest
      run: |
        sudo apt-get install python3-venv -y
        python3 -m venv challenge_venv
        python -m pip install --upgrade pip
        python -m pip install flask
        python -m pip list
        pip install -r requirements.txt
        source challenge_venv/bin/activate
        python tests.py
        
